### ISSUE TITLE
kustomize needs git in PATH

### ISSUE THREAD

**Issue by bradbeam** [abskmj/snapcraft-kustomize#3]
Started running into an issue today while running through our ci workflows. It looks like this snap was recently included in the GitHub Actions virtual environments. When running kustomize against a url, we get the following error:

```
no such file or directory", loader.New "no 'git' program on path: exec: \"git\": executable file not found in $PATH"
```

Example kustomize.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/redskyops/redskyops-recipes/postgres
```
